name = "ip-lookup"
main = "src/index.ts"
compatibility_date = "2024-01-29"

workers_dev = false
#route = { pattern = "ip.rootnet.in/*", zone_name = "rootnet.in" }

[[kv_namespaces]]
binding = "IP2NETWORK"
id = "82f087303aef4469bb17b6b3400df993"
preview_id = "82f087303aef4469bb17b6b3400df993"
